### ISSUE TITLE
Change color of the "Send login link" button on click

### ISSUE THREAD

**Issue by dolebas** [dolebas/issues#83]
Change the colour from bluish to another colour by editing dolebas_subtheme/css/style.css

![image](https://user-images.githubusercontent.com/27515901/29240511-5322854e-7f67-11e7-991f-95c4a3eceb86.png)

**Comment by DmitryFleur** [comment]
codemill$20 

Can this be done using JS or you want only css?

**Comment by dolebas** [comment]
It should be possible to make it happen with css. Style.css is located here
https://github.com/dolebas/dolebas_subtheme/blob/master/css/style.css

If you have or create an account at https://c9.io/ I can provide you with a dev environment.

**Comment by DmitryFleur** [comment]
Here is example of the code that will work, just change with your class name(ex: btn-primary):

```
.btn-success:hover, .btn-success:active, .btn-success:focus { 
  color: #ffffff !important; 
  background-color: #161617 !important; 
  border-color: #494F57 !important;
}
```

But the color will be the same color like it was at the beginning, once user clicks somewhere else. To fix it you should add JS that will add a new class with new background-color once the button is clicked.

**Comment by dolebas** [comment]
Thanks. Will you please create a pull request and I will award you if the code works as expected?

Now the button changes colour when the button is clicked. You can check it out here: https://aug-21-source-jhammars.c9users.io/

**Comment by DmitryFleur** [comment]
then just use this code to make it white:

`background-color: #fff !important;`

and to make a text readable:

`color: #000 !important
`

**Comment by dolebas** [comment]
Please fork, edit the file and create a PR and I will be happy to try it out!

**Comment by dolebas** [comment]
Fixed by https://github.com/dolebas/dolebas_subtheme/pull/9
